# Generated by Django 5.0.3 on 2024-04-03 12:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empcode', models.CharField(max_length=25, null=True)),
                ('empdept', models.CharField(max_length=25, null=True)),
                ('designation', models.CharField(max_length=25, null=True)),
                ('contact', models.CharField(max_length=25, null=True)),
                ('gender', models.CharField(max_length=25, null=True)),
                ('joiningdate', models.CharField(max_length=25, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
